#!/bin/bash -u
#
# hotfix harden-ssh
# hotfix to configure ssh in a more secure manner
#
# usage: ssh [SSH_ARGS] <service-point> sudo -E env "PATH=$PATH:/opt/bluecat/bin/" hotfix harden-ssh

configFile=/etc/ssh/sshd_config.d/bluecat_hardened_ssh.conf

echo setting up $configFile and then restarting ssh service

cat > $configFile << EOF
MACs -hmac-sha2-512,hmac-sha1,hmac-sha1-etm@openssh.com,hmac-sha2-256,umac-128@openssh.com,umac-64-etm@openssh.com,umac-64@openssh.com
Ciphers aes128-ctr,aes192-ctr,aes256-ctr
KexAlgorithms -ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
EOF

systemctl restart ssh
if test "$verbose" = true; then
	echo ""
	echo ssh status:
	systemctl status ssh | cat
fi
